name: CI

on: 
  pull_request:
    branches:	[develop]

jobs:
  app-unit-tests:
    name: app-unit-tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ secrets.CI_ACCESS_TOKEN }}

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21.0.8+9.0.LTS'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Cache Gradle Wrapper and Build Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          !~/.gradle/caches/modules-2/metadata-2.16  # Exclude metadata that changes often
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Tests
      run: ./gradlew test -x lint --no-daemon --stacktrace

  component-instrumentation-tests:
    name: component-instrumentation-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.CI_ACCESS_TOKEN }}

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.8+9.0.LTS'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache Gradle Wrapper and Build Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/modules-2/metadata-2.16  # Exclude metadata that changes often
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Component APK
        run: ./gradlew :components:assembleDebug --no-daemon --stacktrace

      - name: Build Test APK
        run: ./gradlew :tests:assembleDebugAndroidTest --no-daemon --stacktrace

      - name: Verify APK outputs
        run: |
          echo "App APK:"
          find components/build/outputs/apk/debug -name "*.apk"
          echo "Test APK:"
          find tests/build/outputs/apk/androidTest/debug -name "*.apk"

      - name: Run Android tests on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: >
            gcloud firebase test android run
            --type instrumentation
            --app components/build/outputs/apk/debug/components-debug.apk
            --test tests/build/outputs/apk/androidTest/debug/tests-debug-androidTest.apk
            --device model=MediumPhone.arm,version=35,locale=en,orientation=portrait
        env:
          SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
